### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 3: invalid start byte

### ISSUE THREAD

**Issue by PraveenPenguin** [n8henrie/pycookiecheat#31]
- **Operating system and version**: fedora 32 
- **Python version**: 3.8 
- **pycookiecheat version**: pycookiecheat-0.4.5

## My Issue

facing issue on UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 3: invalid start byte

[Praveen@praveenpenguin setup]$ python s.py 
Traceback (most recent call last):
  File "s.py", line 8, in <module>
    cookies = chrome_cookies(url)
  File "/usr/local/lib/python3.8/site-packages/pycookiecheat/pycookiecheat.py", line 279, in chrome_cookies
    val = chrome_decrypt(
  File "/usr/local/lib/python3.8/site-packages/pycookiecheat/pycookiecheat.py", line 71, in chrome_decrypt
    return clean(decrypted)
  File "/usr/local/lib/python3.8/site-packages/pycookiecheat/pycookiecheat.py", line 44, in clean
    return decrypted[:-last].decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 3: invalid start byte
[Praveen@praveenpenguin setup]$ 

[Praveen@praveenpenguin setup]$ cat s.py 
from pycookiecheat import chrome_cookies
import requests

url = 'http://www.google.com'
# Uses Chrome's default cookies filepath by default
cookies = chrome_cookies(url)
r = requests.get(url, cookies=cookies)

print (r)
[Praveen@praveenpenguin setup]$ 

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and pycookiecheat version in your issue
- [x] Ensure you're running a supported version of Python
- [ ] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [x] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Please take a look at my responses in the [existing issues for this error](https://github.com/n8henrie/pycookiecheat/search?q=UnicodeDecodeError&type=issues), let me know if you find anything of interest there.

**Comment by PraveenPenguin** [comment]
@n8henrie thanks for helping ,  i already brows those issues and tried work around but none of help me

**Comment by n8henrie** [comment]
Can you be more specific about what you've tried?

Also, what are your system language and locale settings?

**Comment by PraveenPenguin** [comment]
1- I try to see check it if my system get config loaded  my_pass key but this line returns None

https://github.com/n8henrie/pycookiecheat/blob/master/src/pycookiecheat/pycookiecheat.py#L164-L165 

```
            my_pass = keyring.get_password(
                "{} Keys".format(browser), "{} Safe Storage".format(browser)
            )

````

2- than i try 

https://github.com/n8henrie/pycookiecheat/issues/18#issuecomment-455310992

here also same issue ,

now i bump up my python to 3.9 and fedora system to 33 but still same issue :( 

my system encoding utf-8

[Praveen@praveenpenguin ~]$ python3 -c 'import sys; print(sys.getdefaultencoding())'
utf-8
[Praveen@praveenpenguin ~]$

**Comment by n8henrie** [comment]
Thanks for looking into that. What browser (and browser version) are you
using?

**Comment by PraveenPenguin** [comment]
@n8henrie thanks for help , I am using Google Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by n8henrie** [comment]
I've never used fedora. What desktop environment are you using? Does it have a built-in password manager?

**Comment by PraveenPenguin** [comment]
i am using KDE but i install gnome-kyring

**Comment by n8henrie** [comment]
Sorry this is taking so long.

I just pushed a commit to the `issue_31` branch that should print out the bytes that are causing the error; I'm hoping this will help us debug what encoding it might be using.

Can you install this branch, see if you can recreate the error above, and then consider (privately) sending me the output?

Note that this will probably be a password of yours, possibly an important one, and as such a big security problem. But I don't really know how else to debug it unless you want to see if you can figure out the encoding yourself.

**Comment by PraveenPenguin** [comment]
@n8henrie thanks lot for help , it worked for me as i did update my Browser not sure what was helped here as i used master itself not form pip

**Comment by n8henrie** [comment]
Huh. Well glad it got sorted out!

**Comment by rafaelribeiroo** [comment]
> at was helped here as i used master itself

Did it work on your machine? I'm having the same error and I have no idea what I do to solve this

**Comment by eduardohayashi** [comment]
Im still having the issue, but for /0xce character

Unexpected error: ‘utf-8’ codec can’t decode byte 0xe3 in position 18: invalid continuation byte

$ python -V
Python 3.7.3

$ python3 -c 'import sys; print(sys.getdefaultencoding())'
utf-8

**Comment by ChillerDragon** [comment]
I also started to get this issue after some update. Using chromium on archlinux.

```
$ chromium --version
Chromium 93.0.4577.63 Arch Linux
$ python --version
Python 3.9.6
$ python -m pip freeze | grep cookie
pycookiecheat==0.4.7
```

```
$ python main.py 
Traceback (most recent call last):
  File "/home/chiller/Desktop/pycookie/main.py", line 9, in <module>
    cookies = chrome_cookies(url, browser='chromium')
  File "/home/chiller/.local/lib/python3.9/site-packages/pycookiecheat/pycookiecheat.py", line 278, in chrome_cookies
    val = chrome_decrypt(
  File "/home/chiller/.local/lib/python3.9/site-packages/pycookiecheat/pycookiecheat.py", line 71, in chrome_decrypt
    return clean(decrypted)
  File "/home/chiller/.local/lib/python3.9/site-packages/pycookiecheat/pycookiecheat.py", line 43, in clean
    return decrypted[:-last].decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 1: invalid start byte
```

```python
#!/usr/bin/env python3

from pycookiecheat import chrome_cookies
import requests

url = 'https://github.com/n8henrie/pycookiecheat'

cookies = chrome_cookies(url, browser='chromium')
r = requests.get(url, cookies=cookies)
```

**Comment by n8henrie** [comment]
@ChillerDragon -- sorry for the long response time.

I can run your *identical* code on the same version on Arch with no error. As far as I can tell, these errors have to do with a user's desktop environment and any secrets utilities that it provides.

What desktop are you using?

**Comment by ChillerDragon** [comment]
> @ChillerDragon -- sorry for the long response time.
> 
> 
> 
> I can run your *identical* code on the same version on Arch with no error. As far as I can tell, these errors have to do with a user's desktop environment and any secrets utilities that it provides.
> 
> 
> 
> What desktop are you using?

I used gnome on both machines that I was testing it. Both got the error.

**Comment by ChillerDragon** [comment]
@n8henrie pycookiecheat used to just work fine on all my devices now I can not get it to work anywhere

python-gi is not a debian 11 package. I tried gnome, xfc, i3-gaps and openbox on debian 11 and archlinux. I tried deleting ~/.config/chromium and reinstalling chrome. Either it fails on UnicodeDecodeError or with a SQLite error saying unable to open database.

**Comment by n8henrie** [comment]
Huh, well thanks for trying so many options.

> UnicodeDecodeError or with a SQLite error saying unable to open database.

Those are unrelated errors. See also: <https://github.com/n8henrie/pycookiecheat/issues/29>

Regarding Gnome -- did you try the code I linked? https://github.com/n8henrie/pycookiecheat/issues/23#issuecomment-469474851

I also tried uninstalling gnome-keyring that caused


Sorry you're having trouble. This has happened to several others, and it's not obvious how to debug. It seems to be an issue where decoding the password returns non-UTF8 characters, which seems to mean that something is going wrong in decrypting, which usually means that it is not getting the correct password.

The default password on Linux is `peanuts`. When folks on Linux are using custom secrets solutions (like `gnome-keyring`), it uses something other than this default. Gnome is the only one for whom anyone has contributed code to help use non-default passwords on Linux: https://github.com/n8henrie/pycookiecheat/blob/26fe8449318e6ed8400cc4d0cbe62b2ddacada6b/src/pycookiecheat/pycookiecheat.py#L141

Are you logged into an account through Chromium? If so, can you log out and see if your results are any different?

```console
$ chromium --version
Chromium 94.0.4606.81 Arch Linux
$ uname -r
5.14.11-arch1-1
```

**Comment by n8henrie** [comment]
Sorry for the long delay.

So it looks like it is finding `Chromium Safe Storage`.

Below `print(item.get_label())`, what do you get if you add some additional code from https://github.com/n8henrie/pycookiecheat/blob/26fe8449318e6ed8400cc4d0cbe62b2ddacada6b/src/pycookiecheat/pycookiecheat.py#L149, such as:

```python
item.load_secret_sync()
secret = item.get_secret()
pw_bytes = secret.get()
text = secret.get_text()
print(pw_bytes)
print(text)
```

I'm taking this from:

- <https://lazka.github.io/pgi-docs/#Secret-1/classes/Item.html#Secret.Item.get_secret>
- <https://lazka.github.io/pgi-docs/Secret-1/classes/Value.html#Secret.Value>

(Obviously don't print your output here unless it's a password you don't care about and plan to immediately change.)

**Comment by ChillerDragon** [comment]
```python
#!/usr/bin/env python3
import gi
gi.require_version('Secret', '1')
from gi.repository import Secret

flags = Secret.ServiceFlags.LOAD_COLLECTIONS
service = Secret.Service.get_sync(flags)
gnome_keyring = service.get_collections()
unlocked_keyrings = service.unlock_sync(gnome_keyring).unlocked

for unlocked_keyring in unlocked_keyrings:
        for item in unlocked_keyring.get_items():
                    print("label: %s" % item.get_label())
                    item.load_secret_sync()
                    secret = item.get_secret()
                    pw_bytes = secret.get()
                    text = secret.get_text()
                    print("  bytes: %s" % pw_bytes)
                    print("  text: %s" % text)
```

```
label: Chromium Safe Storage
  bytes: b'L6...=='
  text: L6F..==
label: Chromium Safe Storage
  bytes: b'xUXxjei..=='
  text: xUXxj..==
label: GOA exchange credentials for identity XXX
  bytes: b"{'password': <'pw..==\\n'>}"
  text: {'password': <'pwu..==\n'>}
label: VPN password secret for xxx/org.freedesktop.NetworkManager.openvpn/vpn
  bytes: b'd!Z..
  text: d!Z..
label: Chrome Safe Storage Control
  bytes: b'The meaning of life'
  text: The meaning of life
```

**Comment by n8henrie** [comment]
Thanks for your time, sorry for all the back-and-forth on this.

If you run something like the below,

from pycookiecheat import get_linux_config

print(get_linux_config("Chromium"))

Do you see config[“my_pass”] having the same value as you see above with
under label: Chromium Safe Storage?

I also wonder if having a duplicate Chromium Safe Storage may be an issue.

**Comment by ChillerDragon** [comment]
```python3
#!/usr/bin/env python3

from pycookiecheat.pycookiecheat import get_linux_config

print(get_linux_config("Chromium"))
```

yes same password as the first entry (the L6):

```
{'my_pass': 'L6...==', 'iterations': 1, 'cookie_file': '~/.config/chromium/Default/Cookies'}
```

**Comment by n8henrie** [comment]
What happens if you manually pass in the second `Chromium Safe Storage` password from above? I wonder if it could be breaking because it uses the first password it finds when the second is the correct one?

```python
from pycookiecheat import chrome_cookies

print(chrome_cookies("https://example.com", browser="Chromium", password=b'xUXxjei..=='))
```

**Comment by ChillerDragon** [comment]
```python
#!/usr/bin/env python3

import gi
from pycookiecheat.pycookiecheat import chrome_cookies

gi.require_version('Secret', '1')
from gi.repository import Secret

flags = Secret.ServiceFlags.LOAD_COLLECTIONS
service = Secret.Service.get_sync(flags)
gnome_keyring = service.get_collections()
unlocked_keyrings = service.unlock_sync(gnome_keyring).unlocked
    
for unlocked_keyring in unlocked_keyrings:
    for item in unlocked_keyring.get_items():
        label = item.get_label()
        if label != "Chromium Safe Storage":
            continue
        item.load_secret_sync()
        secret = item.get_secret()
        pw_bytes = secret.get()
        print(f"label: {label}")
        print(f"  bytes: {pw_bytes}")
        try:
            print(chrome_cookies("https://github.com/", browser="Chromium", password=pw_bytes))
        except Exception as e:
            print("Didn't work.")
            print(e)
```

```
label: Chromium Safe Storage
  bytes: b'L6...=='
Didn't work.
'utf-8' codec can't decode byte 0xce in position 1: invalid continuation byte
label: Chromium Safe Storage
  bytes: b'xU...=='
Didn't work.
'utf-8' codec can't decode byte 0x8f in position 1: invalid start byte
```

```
$ uname -a
Linux thinkpad 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux
$ chromium --version
Chromium 96.0.4664.93 Arch Linux
```

**Comment by Samge0** [comment]
same error

**Comment by n8henrie** [comment]
@Samge0 If you're hoping I can figure this out someday, adding some context would be nice. Hardware, OS, desktop environment, browser, version, etc...

After all these years, I have still been unable to reproduce this error on my end, either on multiple versions of MacOS, Arch Linux, or now Ubuntu via Docker -- but enough users have reported it that I'm *sure* it's real, I just need to figure out how to reproduce it so I can take a closer look.

**Comment by n8henrie** [comment]
> I tried gnome, xfc, i3-gaps and openbox on debian 11 and archlinux

@ChillerDragon

I'm still having a hard time reproducing the issue.

I just spent several hours installing a vanilla ubuntu, debian, and arch system (using gnome) in virtualenvs -- pycookiecheat shows no errors on all three (and my native arch-i3 based system as well).

Debian fails to decode the cookies, but it doesn't throw any errors (just returns a dict of `{cookie_name1: "", cookie_name2: ""}`

**Comment by n8henrie** [comment]
@ChillerDragon would you be willing to use e.g. virtualenv to try to recreate your environment in a fresh installation and see what happens? If you're able to recreate the error then perhaps you can tell me the steps you went through so I can see how to reproduce it on my end.

At this point, I don't think I'll be able to work this out unless I can reproduce the error.

**Comment by n8henrie** [comment]
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this as dead. Please feel free to let me know if I should re-open.
